services:
  valart:
    build: .
    container_name: valart
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy 